console.log('hello world');
var h1 = document.querySelector('h1');
console.log(h1);
console.dir(h1);
var explanation = document.querySelector('#explanation');
console.log(explanation);
console.dir(explanation);
var hint = document.querySelector('.hint');
console.log(hint);
console.dir(hint);
var pElementNodeList = document.querySelectorAll('p');
console.log(pElementNodeList);
var exampleLinkClassNodeList = document.querySelectorAll('.example-link');
console.log(exampleLinkClassNodeList);
