var width = 5;
var height = 3;
var area = width * height;
var bill = 100;
var payment = 120;
var change = payment - bill;
var quizzes = 95;
var midterm = 83;
var final = 92;
var grade = (quizzes + midterm + final) / 3;
var firstName = 'Joshua';
var lastName = 'Angeles';
var fullName = firstName + ' ' + lastName;
var pH = 5;
var isAcidic = pH < 7;
var headCount = 14;
var isSparta = headCount === 300;
var motto = fullName;
motto += ' is the GOAT';
console.log('The variable \'area\' is a ' + typeof area + ' and a value of ' + area);
console.log('The variable \'change\' is a ' + typeof change + ' and a value of $' + change);
console.log('The variable \'grade\' is a ' + typeof grade + ' and a value of ' + grade);
console.log('The variable \'fullName\' is a ' + typeof fullName + ' and a value of ' + fullName);
console.log('The variable \'isAcidic\' is a ' + typeof isAcidic + ' and a value of ' + isAcidic);
console.log('The variable \'isSparta\' is a ' + typeof isSparta + ' and a value of ' + isSparta);
console.log('The variable \'motto\' is a ' + typeof motto + ' and a value of ' + motto);
